include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    missing_return: error
    must_be_immutable: error
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: info
    todo: info

  exclude:
    - "lib/src/generated/**"
    - "hook/**"
    - ".dart_tool/**"
    - "build/**"

linter:
  rules:
    # Safety
    avoid_dynamic_calls: true
    discarded_futures: true
    require_trailing_commas: true
    avoid_catches_without_on_clauses: true
    only_throw_errors: true

    # Error prevention
    avoid_print: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style (rules not already in lints/recommended)
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
